/* Generated by tools/mkboot.py from src/apps/hello.fth. */
#ifndef HELLO_FTH_H
#define HELLO_FTH_H
static const char hello_fth[] =
    "\\ hello.fth -- a first program, and a place to start your own.\n"
    "\\\n"
    "\\ Run it: START in Files, or type  INCLUDE HELLO.FTH  at the\n"
    "\\ prompt.  Change it: EDIT HELLO.FTH, then ^S to save.  Your\n"
    "\\ copy goes on the Controller Pak and is the one that runs from\n"
    "\\ then on; delete it and this one comes back.\n"
    "\n"
    ": GREETING\n"
    "   CYAN INK .\" Hello from a file on the Nintendo 64!\" CR\n"
    "   WHITE INK ;\n"
    "\n"
    ": COUNTDOWN ( n -- )\n"
    "   BEGIN DUP 0> WHILE DUP . 1- REPEAT\n"
    "   DROP .\" liftoff\" CR ;\n"
    "\n"
    ": FILES-HERE ( -- )\n"
    "   .\" There are \" #FILES . .\" files, and \"\n"
    "   DISK-FREE . .\" bytes free.\" CR ;\n"
    "\n"
    "GREETING\n"
    "10 COUNTDOWN\n"
    "FILES-HERE\n"
    ;
#endif
