/* Generated by tools/mkboot.py from src/apps/tasks.fth. */
#ifndef TASKS_FTH_H
#define TASKS_FTH_H
static const char tasks_fth[] =
    "\\ tasks.fth -- three programs at once, each in its own window,\n"
    "\\ and a prompt in a fourth.\n"
    "\\\n"
    "\\ Mandelbrot, Life and Navier-Stokes are the same files the\n"
    "\\ desktop opens one at a time.  Here the desk (DESK.FTH) opens\n"
    "\\ all three, and each frame asks every one of them for its next\n"
    "\\ row, into its own window, so they run side by side -- while\n"
    "\\ you type at the prompt underneath.  A line you enter runs\n"
    "\\ there and then; the others wait for it, as they would on any\n"
    "\\ machine with one processor and no preemption.\n"
    "\\\n"
    "\\ Two apps that both define ROW can share one dictionary because\n"
    "\\ Forth binds a call when it compiles it: the moment a file is\n"
    "\\ in, its ROW is the newest ROW, and that is the one the desk\n"
    "\\ keeps.  BYE (or B) goes back to the desktop.\n"
    "\n"
    "INCLUDE DESK.FTH\n"
    "\n"
    ": START\n"
    "   DESK-RESET-XT EXECUTE\n"
    "    16 48 S\" MANDEL.FTH\" OPEN-AT-XT EXECUTE\n"
    "   224 48 S\" LIFE.FTH\"   OPEN-AT-XT EXECUTE\n"
    "   432 48 S\" NAVIER.FTH\" OPEN-AT-XT EXECUTE\n"
    "    16 272 608 176 NEW-PROMPT-XT EXECUTE ;\n"
    ;
#endif
