#!/usr/bin/env python3
"""Turn a .fth source file into a C string the kernel interprets at boot.

    mkboot.py src/system.fth src/system_fth.h system_fth

Comments and blank lines are stripped: every token in the boot source costs
image space and boot time, since the dictionary is searched linearly.
"""
import os
import sys


def strip(src):
    out = []
    for line in src.splitlines():
        # A backslash comment runs to the end of the line, but only when the
        # backslash stands alone as a word.
        parts = []
        for word in line.split():
            if word == "\\":
                break
            parts.append(word)
        line = " ".join(parts)
        if line:
            out.append(line)
    return out


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    raw = "--raw" in sys.argv
    src, dst, sym = args[0], args[1], args[2]
    text = open(src).read()
    # An app's source is shown on screen as well as run, so it keeps its
    # comments and its shape.  Boot sources are stripped.
    lines = text.splitlines() if raw else strip(text)
    guard = os.path.basename(dst).upper().replace(".", "_")

    with open(dst, "w") as f:
        f.write(f"/* Generated by tools/mkboot.py from {src}. */\n")
        f.write(f"#ifndef {guard}\n#define {guard}\n")
        f.write(f"static const char {sym}[] =\n")
        for line in lines:
            esc = line.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'    "{esc}\\n"\n')
        f.write("    ;\n#endif\n")
    total = sum(len(x) + 1 for x in lines)
    print(f"{dst}: {len(lines)} lines, {total} bytes")


if __name__ == "__main__":
    main()
