#!/usr/bin/env python3
"""Rasterise a monospace TTF into an 8x16 1bpp font table -> src/font.h.

96 glyphs, ASCII 0x20..0x7F, 16 bytes each (one byte per row, MSB = leftmost
pixel).  The kernel console draws straight out of this table.
"""
import os
from PIL import Image, ImageDraw, ImageFont

W, H = 8, 16
FIRST, LAST = 0x20, 0x7F
CANDIDATES = [
    ("/System/Library/Fonts/Menlo.ttc", 14),
    ("/System/Library/Fonts/Monaco.ttf", 14),
    ("/System/Library/Fonts/Supplemental/Courier New.ttf", 15),
]


def pick_font():
    for path, size in CANDIDATES:
        if os.path.exists(path):
            return ImageFont.truetype(path, size), path, size
    raise SystemExit("no monospace font found")


def glyph(font, ch, ox, oy):
    img = Image.new("L", (W, H), 0)
    ImageDraw.Draw(img).text((ox, oy), ch, font=font, fill=255)
    rows = []
    for y in range(H):
        b = 0
        for x in range(W):
            if img.getpixel((x, y)) > 110:
                b |= 0x80 >> x
        rows.append(b)
    return rows


def main():
    font, path, size = pick_font()
    # Centre the cell on the font's own metrics.
    box = font.getbbox("M")
    ox = (W - (box[2] - box[0])) // 2 - box[0]
    oy = (H - (box[3] - box[1])) // 2 - box[1]

    glyphs = [glyph(font, chr(c), ox, oy) for c in range(FIRST, LAST + 1)]
    out = [
        "/* Generated by tools/mkfont.py -- do not edit. */",
        f"/* {os.path.basename(path)} @ {size}px, {W}x{H} cell, ASCII"
        f" {FIRST:#04x}..{LAST:#04x} */",
        "#ifndef FONT8X16_H",
        "#define FONT8X16_H",
        f"#define FONT_W_PX {W}",
        f"#define FONT_H_PX {H}",
        f"#define FONT_FIRST {FIRST}",
        f"#define FONT_COUNT {LAST - FIRST + 1}",
        f"static const unsigned char font8x16[FONT_COUNT][{H}] = {{",
    ]
    for c, rows in zip(range(FIRST, LAST + 1), glyphs):
        name = chr(c) if c != 0x7F else "DEL"
        body = ",".join(f"0x{r:02x}" for r in rows)
        out.append(f"    {{{body}}}, /* {c:#04x} {name!r} */")
    out += ["};", "#endif /* FONT8X16_H */", ""]

    dst = os.path.join(os.path.dirname(__file__), "..", "src", "font.h")
    with open(dst, "w") as f:
        f.write("\n".join(out))
    print(f"font.h: {path} @ {size}px, offset ({ox},{oy})")

    for ch in "AbgW!":
        rows = glyphs[ord(ch) - FIRST]
        print(f"--- {ch}")
        for r in rows:
            print("".join("#" if r & (0x80 >> x) else "." for x in range(W)))


if __name__ == "__main__":
    main()
